name: Build and push image to GAR
on:
  release:
    types: [created]
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: swarm-io/action-build-push-image@v1
        with:
          credentials-json: ${{ secrets.GAR_WRITE_SERVICE_ACCOUNT_KEY }}
          project-id: ${{ secrets.GCLOUD_PROJECT_ID_PROD }}
          secrets: |
            GIT_PAT=${{ secrets.GIT_RUNNER_TOKEN }}